---

- name: Calculator
  hosts: all
  become: no
  
  tasks:
    - name: system os detection 
      debug: var=ansible_os_family
      
    - name: Check Java version
      shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
      register: java_version
      
    - name: delete a directory if it exists
      file:
        path: /home/mftiedu/Calculator
        state: absent
      become: yes
      
    - name: Create a directory for project files
      file:
        path: /home/mftiedu/Calculator
        state: directory
        mode: '0777'
      become: yes
    
    - name: Copy jar file
      copy:
        src: ./target/json-reader-1.0-SNAPSHOT.jar
        dest: /home/mftiedu/Calculator/json-reader-1.0-SNAPSHOT.jar
        
        
    - name: Create a directory for libs
      file:
        path: /home/mftiedu/Calculator
        state: directory
        mode: '0777'
      become: yes
      
    - name: Copy libs
      copy:
        src: ./target/libs
        dest: /home/mftiedu/Calculator
        directory_mode: yes
      
    - block: #======Install java======
      - name: CentOs java installation
        yum: update_cache=yes name=java-1.8.0-openjdk-devel state=latest
        when: ansible_os_family == "RedHat"
      - name: Debian java installation
        apt: update_cache=yes name=openjdk-8-jdk-headless state=latest
        when: ansible_os_family == "Debian"
      when: java_version.stdout == "" or java_version.stdout is version('1.8', '<')
      become: yes
      
    - name: launch project
      shell: |
        cd /home/mftiedu/Calculator/
        java -jar json-reader-1.0-SNAPSHOT.jar
...
