---
- hosts: all
  become: yes
  vars_files:
    - ./server_vars.yml
  vars:
    jar: 'Calculator-1.0-SNAPSHOT.jar'
  tasks:
    - name: dir exists
      file: path=/David_Oxygen/ state=directory
    - name: copy jar
      copy:
        src: './../java/target/{{ jar }}'
        dest: '/David_Oxygen/{{ jar }}'
        mode: '0755'
    - name: run jar
      shell: java -jar /David_Oxygen/{{ jar }} > /David_Oxygen/result.txt
